-- =============================================================================
-- GIC Financial Intelligence — Supabase Initial Migration
-- File:    supabase/migrations/001_init.sql
-- Purpose: Create core tables, enable RLS, add indexes.
--          All DDL is idempotent (IF NOT EXISTS / CREATE OR REPLACE).
-- =============================================================================

-- Ensure pgcrypto is available for gen_random_uuid() and crypt().
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- TABLE: users
-- Mirrors the JSON user store in auth/users.json.  Supabase Auth handles JWT;
-- this table holds application-level profile data and hashed passwords for the
-- custom auth layer.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    username      TEXT         NOT NULL UNIQUE,
    password_hash TEXT         NOT NULL,
    role          TEXT         NOT NULL DEFAULT 'user'
                               CHECK (role IN ('admin', 'user')),
    full_name     TEXT,
    email         TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  users IS 'Application user accounts with RBAC role assignment.';
COMMENT ON COLUMN users.password_hash IS 'bcrypt hash via pgcrypto crypt().';
COMMENT ON COLUMN users.role IS 'RBAC role: admin has full access, user has read-only.';

-- ---------------------------------------------------------------------------
-- TABLE: audit_events
-- Append-only log of significant user actions (login, forecast run, etc.).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_events (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type  TEXT         NOT NULL,
    user_id     TEXT,                       -- username or UUID string
    details     JSONB        NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  audit_events IS 'Immutable audit trail of all platform actions.';
COMMENT ON COLUMN audit_events.details IS 'Arbitrary structured payload for the event.';

-- ---------------------------------------------------------------------------
-- TABLE: forecasts
-- Persists results from the commodity / index / elasticity forecast endpoints.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS forecasts (
    id                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    commodity          TEXT         NOT NULL,
    model_type         TEXT         NOT NULL,          -- e.g. 'xgboost', 'ensemble'
    point_forecast     JSONB        NOT NULL DEFAULT '[]',
    metrics            JSONB        NOT NULL DEFAULT '{}',
    feature_importance JSONB        NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  forecasts IS 'Stored forecast outputs for historical comparison and audit.';
COMMENT ON COLUMN forecasts.point_forecast IS 'Array of {date, value} objects.';
COMMENT ON COLUMN forecasts.metrics IS 'Model accuracy metrics: MAE, RMSE, MAPE, R2, etc.';

-- ---------------------------------------------------------------------------
-- TABLE: scenarios
-- Monte-Carlo / what-if simulation runs submitted via /simulation/scenario.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scenarios (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name             TEXT         NOT NULL,
    demand_shock     FLOAT        NOT NULL DEFAULT 0,
    commodity_shock  FLOAT        NOT NULL DEFAULT 0,
    fx_shock         FLOAT        NOT NULL DEFAULT 0,
    mc_stats         JSONB        NOT NULL DEFAULT '{}',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  scenarios IS 'Saved scenario simulation parameters and Monte-Carlo results.';
COMMENT ON COLUMN scenarios.mc_stats IS 'Monte-Carlo output: mean, std, VaR, CVaR, percentiles, etc.';

-- ---------------------------------------------------------------------------
-- TABLE: bias_alerts
-- Forecast bias diagnostics generated by the early-warning layer.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bias_alerts (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    commodity   TEXT         NOT NULL,
    bias_pct    FLOAT        NOT NULL,
    direction   TEXT         NOT NULL CHECK (direction IN ('over', 'under')),
    alert_type  TEXT         NOT NULL,     -- e.g. 'systematic_bias', 'spike'
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  bias_alerts IS 'Automated bias / anomaly alerts from the early-warning module.';

-- =============================================================================
-- ROW-LEVEL SECURITY
-- Enable RLS on every table so that no data is visible by default without an
-- explicit policy.  Application connects via the service-role key and bypasses
-- RLS; the anon / authenticated keys must use policies below.
-- =============================================================================

ALTER TABLE users         ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events  ENABLE ROW LEVEL SECURITY;
ALTER TABLE forecasts     ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenarios     ENABLE ROW LEVEL SECURITY;
ALTER TABLE bias_alerts   ENABLE ROW LEVEL SECURITY;

-- Policy: service role (backend) has unrestricted access via service_role key
-- (service_role bypasses RLS automatically — no explicit policy needed).

-- Policy: authenticated users can read their own user row.
DROP POLICY IF EXISTS "users: read own row" ON users;
CREATE POLICY "users: read own row"
    ON users FOR SELECT
    USING (auth.uid()::text = id::text);

-- Policy: authenticated users can read all forecasts (read-only public layer).
DROP POLICY IF EXISTS "forecasts: read all" ON forecasts;
CREATE POLICY "forecasts: read all"
    ON forecasts FOR SELECT
    TO authenticated
    USING (true);

-- Policy: authenticated users can read all scenarios.
DROP POLICY IF EXISTS "scenarios: read all" ON scenarios;
CREATE POLICY "scenarios: read all"
    ON scenarios FOR SELECT
    TO authenticated
    USING (true);

-- Policy: authenticated users can read all bias_alerts.
DROP POLICY IF EXISTS "bias_alerts: read all" ON bias_alerts;
CREATE POLICY "bias_alerts: read all"
    ON bias_alerts FOR SELECT
    TO authenticated
    USING (true);

-- Policy: authenticated users can read audit_events where they are the actor.
DROP POLICY IF EXISTS "audit_events: read own" ON audit_events;
CREATE POLICY "audit_events: read own"
    ON audit_events FOR SELECT
    TO authenticated
    USING (user_id = auth.uid()::text OR user_id = (
        SELECT username FROM users WHERE id = auth.uid()
    ));

-- =============================================================================
-- INDEXES
-- =============================================================================

-- users
CREATE INDEX IF NOT EXISTS idx_users_username    ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_role        ON users (role);

-- audit_events
CREATE INDEX IF NOT EXISTS idx_audit_events_type       ON audit_events (event_type);
CREATE INDEX IF NOT EXISTS idx_audit_events_user_id    ON audit_events (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_created_at ON audit_events (created_at DESC);

-- forecasts
CREATE INDEX IF NOT EXISTS idx_forecasts_commodity   ON forecasts (commodity);
CREATE INDEX IF NOT EXISTS idx_forecasts_model_type  ON forecasts (model_type);
CREATE INDEX IF NOT EXISTS idx_forecasts_created_at  ON forecasts (created_at DESC);

-- scenarios
CREATE INDEX IF NOT EXISTS idx_scenarios_name        ON scenarios (name);
CREATE INDEX IF NOT EXISTS idx_scenarios_created_at  ON scenarios (created_at DESC);

-- bias_alerts
CREATE INDEX IF NOT EXISTS idx_bias_alerts_commodity   ON bias_alerts (commodity);
CREATE INDEX IF NOT EXISTS idx_bias_alerts_direction   ON bias_alerts (direction);
CREATE INDEX IF NOT EXISTS idx_bias_alerts_created_at  ON bias_alerts (created_at DESC);
